### ISSUE TITLE
[New Core]: Game and Watch

### ISSUE THREAD

**Issue by neil-morrison44** [openfpga-cores-inventory/analogue-pocket#183]
### Core Author username

agg23

### Core .yml snippet

```yml
display_name: Game and Watch
repository: fpga-gameandwatch
filter: agg23.GameAndWatch_.*-Pocket
```
