### ISSUE TITLE
[New Core]: Haunted Castle

### ISSUE THREAD

**Issue by Zichio** [openfpga-cores-inventory/analogue-pocket#192]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Haunted Castle
repository: jtbin
path: pocket/zips/jotego.jtcastle.zip
```
