### ISSUE TITLE
[New Core]: Rastan

### ISSUE THREAD

**Issue by Zichio** [openfpga-cores-inventory/analogue-pocket#194]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Rastan
repository: jtbin
path: pocket/zips/jotego.jtrastan.zip
```
