### ISSUE TITLE
[New Core]: Haunted Castle

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#196]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Haunted Castle
repository: jtcastle
path: pocket/zips/jotego.jtcastle.zip
```
