### ISSUE TITLE
[New Core]: Rastan

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#198]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Rastan
repository: jtrastan
path: pocket/zips/jotego.jtrastan.zip
```
