### ISSUE TITLE
[New Core]: jtbtiger

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#297]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Black Tiger
repository: jtbin
path: pocket/zips/jotego.jtbtiger.zip
```
