### ISSUE TITLE
[New Core]: jotego.jtkiwi

### ISSUE THREAD

**Issue by neil-morrison44** [openfpga-cores-inventory/analogue-pocket#39]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: JTKIWI
repository: jtbin
path: pocket/zips/jotego.jtkiwi.zip
```
