### ISSUE TITLE
[New Core]: Aliens

### ISSUE THREAD

**Issue by mattpannella** [openfpga-cores-inventory/analogue-pocket#408]
### Core Author username

jotego

### Core .yml snippet

```yml
- display_name: Double Dragon II
  repository: jtbin
  path: pocket/zips/jotego.jtaliens.zip
```
