### ISSUE TITLE
[New Core]: Simpsons

### ISSUE THREAD

**Issue by mattpannella** [openfpga-cores-inventory/analogue-pocket#409]
### Core Author username

jotego

### Core .yml snippet

```yml
- display_name: Double Dragon II
  repository: jtbin
  path: pocket/zips/jotego.simson.zip
```
