### ISSUE TITLE
[New Core]: TMNT

### ISSUE THREAD

**Issue by mattpannella** [openfpga-cores-inventory/analogue-pocket#410]
### Core Author username

jotego

### Core .yml snippet

```yml
- display_name: Teenage Mutant Ninja Turtles
  repository: jtbin
  path: pocket/zips/jotego.jttmnt.zip
```
