### ISSUE TITLE
[New Core]: Aliens

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#416]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Aliens
repository: jtbin
path: pocket/zips/jotego.jtaliens.zip
```
