### ISSUE TITLE
[New Core]: The Simpsons

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#418]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: The Simpsons
repository: jtbin
path: pocket/zips/jotego.jtsimson.zip
```
