### ISSUE TITLE
[New Core]: JTCOMSC

### ISSUE THREAD

**Issue by joshcampbell191** [openfpga-cores-inventory/analogue-pocket#42]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: JTCOMSC
repository: jtbin
path: pocket/zips/jotego.jtcomsc.zip
```
