### ISSUE TITLE
[New Core]: System 16b

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#420]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: System 16B
repository: jts16b
path: pocket/zips/jotego.jts16b.zip
```
