### ISSUE TITLE
[New Core]: System 16B

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#423]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: System 16B
repository: jtbin
path: pocket/zips/jotego.jts16b.zip
```
