### ISSUE TITLE
[New Core]: Konami Twin16 System

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#425]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Twin16 System
repository: jtbin
path: pocket/zips/jotego.jts16b.zip
```
