### ISSUE TITLE
[New Core]: jtshanon

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#437]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Super Hang-on
repository: jtshanon
path: pocket/zips/jotego.jtshanon.zip
```
