### ISSUE TITLE
Tiger Road

### ISSUE THREAD

**Issue by joshcampbell191** [openfpga-cores-inventory/analogue-pocket#446]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Tiger Road
repository: jtbin
path: pocket/zips/jotego.jttora.zip
```
