### ISSUE TITLE
[New Core]: Bad Dudes vs. DragonNinja

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#454]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Bad Dudes vs. DragonNinja
repository: jtbin
path: pocket/zips/jotego.jtninja.zip
```
