### ISSUE TITLE
[New Core]: CPS2

### ISSUE THREAD

**Issue by Zichio** [openfpga-cores-inventory/analogue-pocket#461]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: CPS2
repository: jtbin
path: pocket/zips/jotego.jtcps2.zip
```
