### ISSUE TITLE
[New Core]: CPS1.5 Beta

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#464]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: CPS1.5
repository: jtbin
path: pocket/zips/jotego.jtcps15.zip
```
