### ISSUE TITLE
[New Core]: Bubble Bobble

### ISSUE THREAD

**Issue by Zichio** [openfpga-cores-inventory/analogue-pocket#465]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Bubble Bobble
repository: jtbin
path: pocket/zips/jotego.jtbubl.zip
```
