### ISSUE TITLE
[New Core]: Bubble Bobble Beta

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#468]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Bubble Bobble
repository: jtbin
path: pocket/zips/jotego.jtbubl.zip
```
