### ISSUE TITLE
[New Core]: Splatterhouse Beta

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#473]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Splatterhouse
repository: jtbin
path: pocket/zips/jotego.jtshouse.zip
```
