### ISSUE TITLE
[New Core]: Splatterhouse 

### ISSUE THREAD

**Issue by mattpannella** [openfpga-cores-inventory/analogue-pocket#478]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Splatterhouse
repository: jtbin
path: pocket/zips/jotego.jtshouse.zip
```
