### ISSUE TITLE
[New Core]: JTKIWI

### ISSUE THREAD

**Issue by joshcampbell191** [openfpga-cores-inventory/analogue-pocket#48]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: JTKIWI
repository: jtbin
path: pocket/zips/jotego.jtkiwi.zip
```
