### ISSUE TITLE
[New Core]: SEGA System 16A

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#493]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: SEGA System 16A
repository: jts16
path: pocket/zips/jotego.jts16.zip
```
