### ISSUE TITLE
[New Core]: truxton 2

### ISSUE THREAD

**Issue by mattpannella** [openfpga-cores-inventory/analogue-pocket#512]
### Core Author username

Coin-OpCollection

### Core .yml snippet

```yml
display_name: Truxton 2
repository: Distribution-OpenFPGA
filter: atrac17.truxton2_
```
