### ISSUE TITLE
[New Core]: whoopee

### ISSUE THREAD

**Issue by mattpannella** [openfpga-cores-inventory/analogue-pocket#514]
### Core Author username

Coin-OpCollection

### Core .yml snippet

```yml
display_name: Whoopee!!
repository: Distribution-OpenFPGA
filter: atrac17.pipibibs_
```
