### ISSUE TITLE
[New Core]: 1942

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#526]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: 1942
repository: jt1942
path: pocket/zips/jotego.jt1942.zip
```
