### ISSUE TITLE
[New Core]: 1942

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#528]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: 1942
repository: jtbin
path: pocket/zips/jotego.jt1942.zip
```
