### ISSUE TITLE
[New Core]: budude2 gb

### ISSUE THREAD

**Issue by mattpannella** [openfpga-cores-inventory/analogue-pocket#540]
### Core Author username

budude2

### Core .yml snippet

```yml
display_name: budude2 GB
repository: openfgpa-GBC
filter: openfpga-gb-
```
