### ISSUE TITLE
[New Core]: Neo Geo Pocket

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#545]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Neo Geo Pocket
repository: jtbin
path: pocket/zips/jotego.jtngp.zip
```
