### ISSUE TITLE
Jailbreak

### ISSUE THREAD

**Issue by rolandking** [openfpga-cores-inventory/analogue-pocket#593]
### Core Author username

rolandking

### Core .yml snippet

```yml
display_name: Jailbreak Konami 1986
repository: openFPGA-jailbreak
path: releases/download/v1.1/rolandking-Jailbreak-1.1.zip
```
