### ISSUE TITLE
[New Core]: 1943

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#600]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: 1943
repository: jtbin
path: pocket/zips/jotego.jt1943.zip
```
