### ISSUE TITLE
[New Core]: MX5000

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#614]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: MX5000
repository: jtbin
path: pocket/zips/jotego.jtmx5k.zip
```
