### ISSUE TITLE
[New Core]: Karate Champ

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#623]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: CPS1
repository: jtbin
path: pocket/zips/jotego.jtkchamp.zip
```
