### ISSUE TITLE
[New Core]: Commando

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#638]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Commando
repository: jtbin
path: pocket/zips/jotego.jtcommnd.zip
```
