### ISSUE TITLE
[New Core]: 

### ISSUE THREAD

**Issue by rolandking** [openfpga-cores-inventory/analogue-pocket#660]
### Core Author username

rolandking

### Core .yml snippet

```yml
cores:
      display_name: Athena SNK 1986
      repository: openFPGA-Athena
```
