### ISSUE TITLE
[New Core]: Toki

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#669]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Toki
repository: jttoki
path: pocket/zips/jotego.jttoki.zip
```
