### ISSUE TITLE
[New Core]: Toki

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#672]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Toki
repository: jtbin
path: pocket/zips/jotego.jttoki.zip
```
