### ISSUE TITLE
[New Core]: Bionic Commando

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#705]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Bionic Commando
repository: jtbin
path: pocket/zips/jotego.jtbiocom.zip
```
