### ISSUE TITLE
API Changes

### ISSUE THREAD

**Issue by joshcampbell191** [openfpga-cores-inventory/analogue-pocket#710]
@mattpannella @neil-morrison44 

I've been making some progress on refactoring the updater codebase to introduce some new features (APIs, category landing pages, author landing pages, etc.). 

While looking into the `cores.yml`, I noticed that we're still tracking the `prerelease` and `tag_name` for repositories that are using releases as a deployment strategy. Are either of you using these? I'm pretty sure these were created prior to the `download_url` so I doubt they have much use (other than additional metadata).

Are you guys okay if we axe them?

```yml
- username: agg23
  cores:
  - id: agg23.Arduboy
    display_name: Arduboy for Analogue Pocket
    repository:
      platform: github
      name: openfpga-arduboy
      prerelease: false
      tag_name: 0.9.0
    requires_license: false
    download_url: https://github.com/agg23/openfpga-arduboy/releases/download/0.9.0/agg23.Arduboy.0.9.0.zip
    platform_id: arduboy
    description: A small, portable Arduino console.
    version: 0.9.0
    date_release: '2022-09-03'
    platform:
      category: Handheld
      name: Arduboy
      manufacturer: Arduboy
      year: 2016
    assets:
    - platform: arduboy
      extensions:
      - hex
    sponsor:
      github:
      - https://github.com/sponsors/agg23
```
