### ISSUE TITLE
[New Core]: Sly Spy

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#719]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Sly Spy
repository: jtbin
path: pocket/zips/jotego.jtslyspy.zip
```
