### ISSUE TITLE
[New Core]: Fast Lane

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#738]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Fast Lane
repository: jtbin
path: pocket/zips/jotego.jtflane.zip
```
