### ISSUE TITLE
[New Core]: Sunset Riders

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#750]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Sunset Riders
repository: jtbin
path: pocket/zips/jotego.jtriders.zip
```
