### ISSUE TITLE
[New Core]: Trick Trap/Labyrinth Runner

### ISSUE THREAD

**Issue by Zichio** [openfpga-cores-inventory/analogue-pocket#760]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Trick Trap
repository: jtbin
path: pocket/zips/jotego.jtlabrun.zip
```
