### ISSUE TITLE
[New Core]: Parodius Da!

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#773]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Parodius Da!
repository: jtbin
path: pocket/zips/jotego.jtparoda.zip
```
