### ISSUE TITLE
[New Core]: Neo Geo Pocket Color

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#774]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Neo Geo Pocket Color
repository: jtbin
path: pocket/zips/jotego.jtngpc.zip
```
