### ISSUE TITLE
[New Core]: Circus Charlie

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#775]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Circus Charlie
repository: jtbin
path: pocket/zips/jotego.jtcircus.zip
```
