### ISSUE TITLE
[New Core]: WWF Superstars

### ISSUE THREAD

**Issue by espiox** [openfpga-cores-inventory/analogue-pocket#788]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: WWF Superstars
repository: jtbin
path: pocket/zips/jotego.jtwwfss.zip
```
