### ISSUE TITLE
[New Core]: The Speed Rumbler

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#793]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: The Speed Rumbler
repository: jtbin
path: pocket/zips/jotego.jtrumble.zip
```
