### ISSUE TITLE
[New Core]: Midnight Resistance

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#806]
### Core Author username

jotego

### Core .yml snippet

```yml
display_name: Midnight Resistance
repository: jtbin
path: pocket/zips/jotego.jtmidres.zip
```
