### ISSUE TITLE
[New Core]: Double Dragon III

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#808]
### Core Author username

Coin-OpCollection

### Core .yml snippet

```yml
display_name: Double Dragon III
repository: Distribution-OpenFPGA
filter: pram0d.doubledragoniii_
```
