### ISSUE TITLE
[New Core]: WWF WrestleFest

### ISSUE THREAD

**Issue by davewongillies** [openfpga-cores-inventory/analogue-pocket#809]
### Core Author username

Coin-OpCollection

### Core .yml snippet

```yml
display_name: WWF WrestleFest
repository: Distribution-OpenFPGA
filter: pram0d.wrestlefest_
```
