### ISSUE TITLE
[New Core]: NARC

### ISSUE THREAD

**Issue by atrac17** [openfpga-cores-inventory/analogue-pocket#811]
### Core Author username

Coin-OpCollection

### Core .yml snippet

```yml
display_name: NARC
repository: Distribution-OpenFPGA
filter: pram0d.zunit_
```
