### ISSUE TITLE
[New Core]: Smash TV

### ISSUE THREAD

**Issue by atrac17** [openfpga-cores-inventory/analogue-pocket#812]
### Core Author username

Coin-OpCollection

### Core .yml snippet

```yml
display_name: Smash TV
repository: Distribution-OpenFPGA
filter: pram0d.yunit_
```
